### ISSUE TITLE
Failed to prune, and get error "no snapshot paired state".

### ISSUE THREAD

**Issue by hubv** [maticnetwork/bor#1104]
#### **System information**

Bor client version: v1.2.0 & v1.2.0-beta2
Heimdall client version: v1.0.3

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Sentry

#### **Overview of the problem**

Bor client can't prune the database because of "no snapshot paired state" after we upgrading to v1.2.0.
There is no  "Unclean shutdown" and we stopped the node gracefully before the pruning.

#### **Logs / Traces / Output / Error Messages**

Error Log
 
```
bin/bor  snapshot  prune-state  -datadir.ancient   /data01/bor/.bor/bor/chaindata/ancient -datadir  /data01/bor/.bor/  
ERROR[12-10|06:38:18.699] Failed to prune state                    err="no snapshot paired state"

```
![1](https://github.com/maticnetwork/bor/assets/16233859/e6591007-c999-4d36-94c0-9710e10331c6)

Logs of Node

![2](https://github.com/maticnetwork/bor/assets/16233859/c08b76c4-b207-4d21-a118-820acc867eaf)

**Comment by svauve** [comment]
Hi @hubv 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [Defi protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by klestrong** [comment]
I have the same issue also.  I even downloaded the latest Bor snapshot (https://snapshots.polygon.technology/ | 2023-12-02 14:01) and tried to prune after syncing back up.  I resolved the issue by walking back the code past Bor v1.1.0 until I was able to prune Bor successfully with Bor v1.0.6.  Bor v1.1.0 also failed to prune with the same error.

**Comment by Cognacy** [comment]
@klestrong Are you still experiencing this same issue?

**Comment by klestrong** [comment]
@Cognacy 
Yes.  Just earlier today Bor prune failed with v1.2.0 and v1.1.0.  I'm currently able to prune with v1.0.6.  I'm sure I'm doing graceful shutdown as I wait for Bor log to indicate the application stopped and my log session ends the docker container before I stop (delete) it.

When Bor prune fails, I get the same message as the original poster, @hubv .

My docker run is below:
```
docker run --rm -p 30303:30303 -p 8545:8545 -v /mnt/bor-pv:/bor:rw --net polygon --name bor -d <my bor image> server --datadir /bor --port 30303 --bor.heimdall 'http://heimdallr:1317' --http --http.addr '0.0.0.0' --http.vhosts '*' --http.corsdomain '*' --http.port 8545 --ipcpath /bor/bor.ipc --http.api 'eth,net,web3,txpool,bor' --syncmode 'full' --cache '4096' --miner.gasprice '30000000000' --miner.gaslimit '20000000' --txpool.nolocals --txpool.accountslots 16 --txpool.globalslots 32768 --txpool.accountqueue 16 --txpool.globalqueue 32768 --txpool.pricelimit '30000000000' --maxpeers 200 --bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"
```

My prune command is below:
```
docker run --rm -it -v /mnt/bor-pv:/datadir 0xpolygon/bor:1.2.0 snapshot prune-state --datadir=/datadir
```

**Comment by Napba** [comment]
@klestrong Hi @klestrong 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [Defi protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by klestrong** [comment]
@Cognacy 
Pruning with previous version v1.0.6 did not resolve the issue.  I'm still unable to prune Bor.  Pruning with the mentioned version took abnormally long and resulted in disabling Bor as it will no longer sync.  Please see captured errors.  I'm pulling from a backup, but am still unable to prune.  Do you guys have a resolution for this?
![image](https://github.com/maticnetwork/bor/assets/102823326/1fb27e6d-55f7-41f0-8d9e-137febf6ea22)

**Comment by drcliche** [comment]
Same issue exists on 1.3.6.

**Comment by klestrong** [comment]
@drcliche 
I executed as you described, prune using v1.1.0 after letting letting it snapshot.  The prune was successful and Bor synced up afterwards.  Thanks for the assist, much appreciated.

**Comment by pratikspatil024** [comment]
Thanks for reporting, guys.
We have identified the issue and it has been fixed in [PR#1110](https://github.com/maticnetwork/bor/pull/1110).

**Comment by odannis** [comment]
I tried the version 1.2.1, but it didn't solve the problem. I still got the error "no snapshot paired state"

**Comment by temaniarpit27** [comment]
We will be soon releasing a fix for this in early first week of January.

**Comment by odannis** [comment]
Ok nice, but downgrading to v1.10 works !
