### ISSUE TITLE
Bor stopped syncing

### ISSUE THREAD

**Issue by Skryabin-P** [maticnetwork/bor#1898]
Bor version 0xpolygon/bor:2.5.0
Network mainnet

bor  | WARN [11-19|18:30:44.226] Network response id collision            have=da2eb34d342a186110c99851b404464cade73efdac173b3a9f4dad6d0b383f21:eth/69:5 want=da2eb34d342a186110c99851b404464cade73efdac173b3a9f4dad6d0b383f21:eth/69:6
bor  | WARN [11-19|18:30:44.226] Synchronisation failed, dropping peer    peer=c0cd797db4ba55a9b407c12820cf1e8693c6149a1ddc7c66db8b821c52126fda err="retrieved hash chain is invalid: invalid merkle root (remote: 4f176275bf3aa1f9cd2d26802aa48522977fd1c0fa28f6bfb7d670bd0b72abce local: 6ded97b94d9ff0014d6d9976761f6286c389d3d26274cf0e6f09e826d543fa85) dberr: %!w(<nil>)"
bor  | INFO [11-19|18:30:46.198] Whitelisting new milestone from heimdall block=79,234,808 hash=63dfe0..91d838
bor  | INFO [11-19|18:30:50.339] Starting span check due to longer than expected block time "target block"=79,234,960 parentHeader=6adaa5..264742 parentHeaderAuthor=0xcA4793C93A94E7A70a4631b1CecE6546e76eb19e targetHeaderAuthor=0xcA4793C93A94E7A70a4631b1CecE6546e76eb19e
bor  | INFO [11-19|18:30:54.198] Whitelisting new milestone from heimdall block=79,234,810 hash=7125c0..99cb3d
bor  | INFO [11-19|18:31:02.340] Span check complete                      foundNewSpan=false
bor  | WARN [11-19|18:31:06.437] Truncating freezer table                 database=/bor-home/bor/chaindata/ancient/chain table=headers items=74,591,292 limit=74,562,241
bor  | WARN [11-19|18:31:06.442] Truncating freezer table                 database=/bor-home/bor/chaindata/ancient/chain table=bodies items=74,592,036 limit=74,562,241
bor  | WARN [11-19|18:31:06.586] Truncating freezer table                 database=/bor-home/bor/chaindata/ancient/chain table=receipts items=74,592,074 limit=74,562,241
bor  | ERROR[11-19|18:31:06.789] Error in block freeze operation          err="block receipts missing, can't freeze block 74592112"
bor  | INFO [11-19|18:31:06.792] Whitelisting new milestone from heimdall block=79,234,811 hash=bb81e9..e207f6
bor  | INFO [11-19|18:31:06.883] Fetching state updates from Heimdall     fromID=3,116,447 to=2025-11-19T17:53:43Z
bor  | INFO [11-19|18:31:06.883] Fetching state sync events               queryParams="from_id=3116447&to_time=2025-11-19T17:53:43Z&pagination.limit=50"
bor  | INFO [11-19|18:31:06.885] StateSyncData                            gas=0         number=79,234,960 lastStateID=3,116,446 "total records"=0  "fetch time"=10 "process time"=0
bor  | INFO [11-19|18:31:06.938] Skip duplicated bad block                number=79,234,960 hash=ac3fb9..87b80e
bor  | ERROR[11-19|18:31:06.940] 
bor  | ########## BAD BLOCK #########
bor  | Block: 79234960 (0xac3fb9d3f3dc20e5ff43df5cf93381c61c95501741abdb7523a88e904987b80e)
bor  | Error: invalid merkle root (remote: 4f176275bf3aa1f9cd2d26802aa48522977fd1c0fa28f6bfb7d670bd0b72abce local: 6ded97b94d9ff0014d6d9976761f6286c389d3d26274cf0e6f09e826d543fa85) dberr: %!w(<nil>)
bor  | Platform: geth v1.14.14-0.20251117095522-b365efe16349+dirty go1.24.6 amd64 linux
bor  | VCS: b365efe1-20251117 (dirty)
bor  | Chain config: &params.ChainConfig{ChainID:137, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:true, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:3395000, MuirGlacierBlock:3395000, BerlinBlock:14750000, LondonBlock:23850000, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiBlock:50523000, CancunBlock:54876000, PragueBlock:73440256, VerkleBlock:<nil>, OsakaBlock:<nil>, TerminalTotalDifficulty:<nil>, DepositContractAddress:0x0000000000000000000000000000000000000000, EnableVerkleAtGenesis:false, Bor:(*params.BorConfig)(0x79775a0), Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), BlobScheduleConfig:(*params.BlobScheduleConfig)(nil)}
bor  | WARN [11-19|18:35:32.890] Synchronisation failed, dropping peer    peer=4ffd6845114e4e1161df5e36696e09f231c1ea900e340591c5d6d00e69af9d2e err="retrieved hash chain is invalid: invalid merkle root (remote: 4f176275bf3aa1f9cd2d26802aa48522977fd1c0fa28f6bfb7d670bd0b72abce local: 6ded97b94d9ff0014d6d9976761f6286c389d3d26274cf0e6f09e826d543fa85) dberr: %!w(<nil>)"
bor  | INFO [11-19|18:35:35.641] Starting span check due to longer than expected block time "target block"=79,234,960 parentHeader=6adaa5..264742 parentHeaderAuthor=0xcA4793C93A94E7A70a4631b1CecE6546e76eb19e targetHeaderAuthor=0xcA4793C93A94E7A70a4631b1CecE6546e76eb19e
bor  | INFO [11-19|18:35:38.199] Whitelisting new milestone from heimdall block=79,234,852 hash=31fb6c..2490af

**Comment by Skryabin-P** [comment]
It started occuring a week ago on [v2.3.3](https://github.com/0xPolygon/bor/releases/tag/v2.3.3) and simple restart did the trick, but it was every day. 
I have upgraded to v.2.5.0 thinking may be you fixed that but it occured an hour ago and restart didn't help at all

I see the bad block error as well as bad peers error, but i don't understand what should i do to fix this

**Comment by marcello33** [comment]
This should be solved. @Skryabin-P  have you tried deleting the chaindata and re-syncing?

**Comment by Skryabin-P** [comment]
@marcello33 Hello! Yes, it is been solved when i upgraded to 2.5.1 and didn't occur since that . Thank you!

**Comment by vanpt1114** [comment]
```
WARN [12-21|12:19:37.005] Truncating freezer table                 database=/bor-home/bor/chaindata/ancient/chain table=bodies items=74,592,036 limit=74,562,241
WARN [12-21|12:19:37.154] Truncating freezer table                 database=/bor-home/bor/chaindata/ancient/chain table=receipts items=74,592,074 limit=74,562,241
WARN [12-21|12:19:37.362] Truncating freezer table                 database=/bor-home/bor/chaindata/ancient/chain table=headers items=74,591,292 limit=74,562,241
ERROR[12-21|12:19:37.367] Error in block freeze operation          err="block receipts missing, can't freeze block 74592112"
```


Not sure why I was still facing this issue, although I used the latest binary. The block is still syncing, but at some time, the syncing process would be stuck for about 5s -> 10s when the above logs occur.
